views:
  - output: "index.html"
    template: "index.html"
  - output: "en/index.html"
    template: "en_index.html"
  - output: "zh/index.html"
    template: "zh_index.html"
  - output: "static/index.html"
    template: "static.html"
  - output: "en/organizations.html"
    query: "en_organizations.rq"
    template: "org_index.html"
  - output: "en/collections.html"
    query: "en_collections.rq"
    template: "collections_index.html"
  - output: "en/{{qid}}.html"
    query: "en_collections.rq"
    template: "collection.html"
  - output: "en/{{qid}}.html"
    query: "en_organizations.rq"
    template: "organization.html"
  - output: "zh/organizations.html"
    query: "zh_organizations.rq"
    template: "org_index.html"
  - output: "zh/{{qid}}.html"
    query: "zh_collections.rq"
    template: "collection.html"
  - output: "zh/{{qid}}.html"
    query: "zh_organizations.rq"
    template: "organization.html"
  - output: "zh/collections.html"
    query: "zh_collections.rq"
    template: "collections_index.html"
  - output: "en/people.html"
    query: "en_people.rq"
    template: "people_index.html"
  - output: "zh/people.html"
    query: "zh_people.rq"
    template: "people_index.html"
  - output: "en/{{qid}}.html"
    query: "en_people.rq"
    template: "person.html"
  - output: "zh/{{qid}}.html"
    query: "zh_people.rq"
    template: "person.html"
  - output: "en/subjects.html"
    query: "en_subjects.rq"
    template: "subjects_index.html"
  - output: "en/materials.html"
    query: "en_materials.rq"
    template: "materials_index.html"